# Generated by Django 5.2.5 on 2025-08-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка на статью')),
                ('published', models.DateTimeField(verbose_name='Дата публикации')),
                ('source', models.CharField(default='lenta', max_length=50, verbose_name='Источник')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст статьи (превью)')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-published'],
            },
        ),
    ]
