name: Deploy to Docker Hub

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: xomamdk/page-parsing
  DOCKER_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build \
          --tag $DOCKER_IMAGE:$DOCKER_TAG \
          .

    - name: Run tests in container
      run: |
        docker run --rm $DOCKER_IMAGE:$DOCKER_TAG python manage.py test --noinput

    - name: Docker Hub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: |
        docker push–≤ $DOCKER_IMAGE:$DOCKER_TAG